import "./globals.css";

export const metadata = {
  // title: "Nextjs tutorial",
  title: {
    default: "Name",
    template: "%s | Name",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" font-poppins"> {children} </body>
    </html>
  );
}
